# DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://mysql:3306/patientmonitoring
spring.datasource.username=root
spring.datasource.password=qwerty@121005

# JPA SETTINGS
spring.jpa.hibernate.ddl-auto=update