spring.application.name=eventplanapp
spring.datasource.url=jdbc:mysql://localhost:3306/eventdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=qwerty@121005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081
jwt.secret=eventplanapp-dev-secret-change-me-32chars
jwt.expiration-ms=86400000

app.backend-url=http://localhost:8081
app.frontend-url=http://localhost:5173

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:pthangaraj865@gmail.com}
spring.mail.password=${MAIL_PASSWORD:iozhnyrlbzledhgx}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
